l_portuguese:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ segundos"
 # Graphics
 SETTING_RENDERER:0 "Renderizador"
 SETTING_VSYNC:0 "VSync"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Faz com que o jogo e o monitor tenham a mesma taxa de quadros, reduzindo distorções da tela.\n\nDesligá-lo pode aumentar o desempenho."
 SETTING_MULTI_SAMPLING:0 "Antisserrilhamento (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!O uso de antisserrilhamento de várias amostras (MSAA) suavizará as bordas das imagens.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_ANTI_ALIASING:0 "Antisserrilhamento"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!O uso de anti-aliasing tornará as bordas das imagens mais suaves.\n\nFXAA é recomendado."
 OPTION_ANTI_ALIASING_DISABLED:0 "Desativado"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Filtragem de textura"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!O uso da filtragem anisotrópica melhora a aparência das superfícies texturizadas.\n\nConfigurações mais baixas podem melhorar o desempenho."
 SETTING_FULLSCREEN_RESOLUTION:0 "Resolução"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:2 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Define a qualidade da imagem do jogo.\n\nResoluções mais baixas podem aumentar o desempenho."
 SETTING_WINDOWED_RESOLUTION:0 "Resolução em Janela"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:0 "Resolução do jogo. Resolução mais alta é mais exigente."
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Se o seu computador tiver vários monitores, escolha aquele que será usado pelo jogo."
 SETTING_GRAPHICS_DEVICE:0 "Placa Gráfica"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Seleciona qual placa gráfica o jogo usará. \n\nO uso de uma placa gráfica integrada ou renderizador de software pode diminuir o desempenho."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Qualidade da Sombra"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Determina a resolução com que os mapas de sombra são renderizados, se as sombras estiverem ativadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_DISPLAY_MODE:0 "Modo de Exibição"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Determina como exibir o jogo em sua tela"
 SETTING_BLOOM:0 "Bloom"
 SETTING_MESH_LOD_BIAS:0 "Qualidade LOD de Malha"
 SETTING_MESH_LOD_FADE:0 "Desvanecer de LOD de malha"
 SETTING_TERRAIN_SMOOTHING:1 "Suavização de Terreno"
 OPTION_FULLSCREEN:0 "Tela Cheia"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Exiba o jogo usando a tela inteira. A definição de Resolução mudará a nitidez da imagem."
 OPTION_WINDOWED:0 "Janela"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Exiba o jogo em uma janela. A definição de Resolução altera o tamanho da janela."
 OPTION_DISABLED:1 "Desativado"
 OPTION_OFF:0 "Desligado"
 OPTION_LOW:0 "Baixo"
 OPTION_MEDIUM:0 "Médio"
 OPTION_HIGH:0 "Alto"
 OPTION_ULTRA:1 "Ultra"
 OPTION_CUSTOM:0 "Personalizado"
 OPTION_DEFAULT:1 "Padrão"
 SETTINGS_CATEGORY_UI:0 "Interface"
 SETTINGS_CATEGORY_GAME:0 "Jogo"
 SETTING_TEXTURE_QUALITY:1 "Qualidade da Textura"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nControla a resolução das texturas carregadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_QUALITY:0 "Predefinição de Qualidade"
 SETTING_SFX:0 "Efeitos Sonoros"
 SETTING_UI:0 "Interface"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Selecione uma predefinição das opções gráficas avançadas abaixo.\n\nUma predefinição baixa aumentará o desempenho."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Ativa um efeito "bloom", em que luzes extremamente brilhantes se espalham para outras partes da imagem.\n\nDesligá-lo pode aumentar o desempenho."
 SETTING_REFRACTION_TOOLTIP:0 "Determina se as refrações aparecem na água ou não."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nControla a qualidade das refrações da água se estiverem ativadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nDetermina o nível mais alto de qualidade dos objetos de mapa (como edifícios).\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nDetermina a qualidade dos LODs (níveis de detalhe) em objetos de mapa, como modelos de unidade.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Se ativado, os modelos 3D transitam suavemente entre diferentes níveis de detalhe (LOD) quando você aumenta ou diminui a ampliação.\n\nDesligá-lo pode aumentar o desempenho."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Determina como os nomes das Cidades e Províncias aparecem no mapa."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Determina se o terreno intransponível está incluído dentro das fronteiras de uma nação no mapa."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nDetermina o idioma da interface do usuário."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "E-mail da sua conta Paradox"
 SETTING_FRAMERATE_CAP:1 "FPS Máximo"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nFPS máximo (quadros por segundo) que o jogo renderizará.\n\nConfigurações mais baixas podem diminuir o consumo de energia."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 # GUI
 SETTING_ANIMATION_SPEED:0 "Velocidade da animação"
 SETTING_GUI_SCALING:0 "Dimensionamento de GUI"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Define a escala de toda a interface do usuário. Útil para resoluções de tela mais altas.\n\n#X Definir um valor muito alto fará com que as interfaces não caibam corretamente na tela!#!"
 # System
 SETTING_MOUSE_PANNING:0 "Rolagem de Borda da Tela"
 SETTING_MOUSE_PANNING_TOOLTIP:3 "#T $SETTING_MOUSE_PANNING$\n#!Define se o mapa deve rolar se o cursor do mouse estiver na borda da tela ou janela."
 SETTING_SCROLL_SPEED:0 "Velocidade de rolagem"
 SETTING_CAMERA_ROTATION_SPEED:0 "Velocidade de rotação da câmera"
 SETTING_ZOOM_SPEED:0 "Velocidade da ampliação"
 SETTING_INPUT_DEVICE:0 "Dispositivo de entrada"
 SETTING_EDITOR:0 "Editor"
 SETTING_EDITOR_POSTFIX:0 "Pós-fixação do editor"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Comando de abertura do editor"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Exibir comando de registro"
 SETTING_GRACEFUL_EXIT:0 "Saída graciosa"
 SETTING_LANGUAGE:0 "Idioma"
 MOUSE_AND_KEYBOARD:0 "Rato e teclado"
 GAMEPAD:0 "Controle"
 SETTING_MULTISAMPLING_DISABLED:0 "Desativado"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Desativado"
 # Editor
 SETTING_CAMERA_TILT:0 "Inclinação da câmera"
 SETTING_CAMERA_STRATEGY:0 "Tipo de câmera"
 SETTING_CENTERED_ZOOM_IN:0 "Ampliação centrada"
 SETTING_CAMERA_SPEED:0 "Velocidade da câmera"
 CAMERA_TABLETOP:0 "Tampo da mesa"
 CAMERA_FPS:0 "Primeira pessoa"
 CAMERA_WASD:0 "Estilo WASD"
 # Audio
 SETTING_Music:0 "Música"
 SETTING_Ambient:0 "Ambiente"
 SETTING_Effects:0 "Efeitos"
 SETTING_Master:0 "Principal"
 SETTING_Master_TOOLTIP:0 "#T Volume Principal\n#!Define o volume de todos os sons do jogo."
 SETTING_Music_TOOLTIP:0 "#T Volume da Música\n#!Define o volume da música."
 SETTING_Ambient_TOOLTIP:0 "#T Volume Ambiente\n#!Define o volume do ambiente."
 SETTING_SFX_TOOLTIP:0 "#T Volume de Efeitos Sonoros\n#!Define o volume de efeitos sonoros, como em combate."
 SETTING_UI_TOOLTIP:0 "#T Volume de Interface\n#!Define o volume da interface do usuário."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Nível de registro de depuração"
 # Game
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Define com que frequência o jogo será salvo automaticamente."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Determina se os salvamentos automáticos são salvos na nuvem ou não."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Determina se a câmera sempre estará voltada para o norte ou não."
 NO_AUTOSAVE:0 "Sem Salvamento Automático"
