l_portuguese:
 SETTING_HINTS:0 "Dicas"
 SETTING_LAST_HOST:0 "Último anfitrião"
 SETTING_LAST_PLAYER:0 "Último jogador"
 SETTING_DIFFICULTY:0 "Dificuldade"
 SETTING_AUTOSAVE:0 "Intervalo de salvamentos automática"
 SETTING_DEBUG_SAVES:0 "Número de salvamentos de depuração"
 SETTING_WINDOW_MOVE_TIME:0 "Tempo de movimento da janela"
 SETTING_RADIAL_STAY_TIME:0 "Tempo de permanência radial"
 SETTING_CAMERA_FACE_NORTH:0 "Câmera voltada para o norte"
 SETTING_AUTOSAVE_TO_CLOUD:0 "Salvar automaticamente na nuvem"
 SETTING_DISABLED_ALERTS:0 "Alertas desativados"
 SETTING_DISABLED_HINTS:0 "Dicas desativadas"
 SETTING_FOCUS_ON_COMBAT:0 "Foco no combate"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP:0 "Determina se a velocidade do jogo deve ser restringida ao observar um combate."
 SETTING_PROVINCE_NAMES:0 "Nomes de província"
 SETTING_MAX_TICKS_AHEAD:0 "Máximo de tiques à frente"
 MAPNAME_MODE_ALWAYS_ON:0 "Sempre ativado"
 MAPNAME_MODE_ALWAYS_OFF:0 "Sempre desativado"
 MAPNAME_MODE_MOUSE_OVER:0 "Passe o rato por cima"
 MAPNAME_MODE_DEFAULT:0 "Padrão"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN:0 "Preencher terreno intransponível"
 SETTING_PAUSE_ON_EVENTS:0 "Pausar em eventos"
 SETTING_ADVICE:0 "Conselho em alerta"
 SETTING_ADVICE_TOOLTIP:0 "Determina se conselhos e destaques serão mostrados ao clicar em um ícone de alerta"
  # Map
 SETTING_DRAW_TERRAIN:0 "Desenhar terreno"
 SETTING_DRAW_WATER:0 "Desenhar água"
 SETTING_DRAW_BORDERS:0 "Desenhar fronteiras"
 SETTING_DRAW_TREES:0 "Desenhar árvores"
 SETTING_DRAW_RIVERS:0 "Desenhar rios"
 SETTING_DRAW_POSTFX:0 "Desenhar pós-processamento"
 SETTING_DRAW_SKY:0 "Desenhar céu"
 SETTING_DRAW_BLOOM:0 "Desenhar bloom"
 SETTING_DRAW_TOOLTIPS:0 "Desenhar dicas de ferramentas"
 SETTING_DRAW_CITYSPRAWL:0 "Desenhar expansão da cidade"
 SETTING_DRAW_SHADOWS:0 "Desenhar sombras"
  # Outliner
 SETTING_OUTLINER_SHOW_OUTLINER:0 "Mostrar delineador"
 SETTING_OUTLINER_PLAYER_ARMIES:0 "Mostrar exércitos de jogadores"
 SETTING_OUTLINER_PLAYER_NAVIES:0 "Mostrar marinhas de jogadores"
 SETTING_OUTLINER_AUTOMATED_NAVIES:0 "Mostrar marinhas do jogador"
 SETTING_OUTLINER_AUTOMATED_ARMIES:0 "Mostrar marinhas do jogador"
 SETTING_OUTLINER_PROVINCIAL_ARMIES:0 "Mostrar marinhas do jogador"
 SETTING_OUTLINER_COMBATS:0 "Mostrar combates"
 SETTING_OUTLINER_SIEGES_OUR:0 "Mostrar nossos cercos"
 SETTING_OUTLINER_SIEGES_HOSTILE:0 "Mostrar cercos hostis"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS:0 "Mostrar personagens desleais"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS:0 "Mostrar construções de edifícios"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY:0 "Mostrar construções militares"
 SETTING_OUTLINER_PROVINCEMODIFIER:0 "Mostrar melhorias de território"
 SETTING_OUTLINER_ACTIVE_WARS:0 "Mostrar guerras ativas"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY:0 "Mostrar diplomacia ativa"
 SETTING_OUTLINER_HUMAN_PLAYERS:0 "Mostrar jogadores humanos"
