l_portuguese:
 SETTINGS_PAGE_GRAPHICS:0 "Gráficos"
 SETTINGS_PAGE_GAME:0 "Jogo"
 SETTINGS_PAGE_SYSTEM:0 "Sistema"
 SETTINGS_PAGE_CONTROLS:0 "Controles"
 SETTINGS_PAGE_EDITOR:0 "Editor"
 SETTINGS_PAGE_INTERFACE:0 "Interface"
 SETTINGS_PAGE_AUDIO:0 "Áudio"
 SETTINGS_CATEGORY_SCREEN:0 "Tela"
 SETTINGS_CATEGORY_QUALITY:0 "Qualidade"
 OPTION_EASY:0 "Fácil"
 OPTION_NORMAL:0 "Normal"
 OPTION_HARD:0 "Difícil"
 OPTION_NEVER:0 "Nunca"
 OPTION_MONTHLY:0 "Todo mês"
 OPTION_HALFYEAR:0 "Todo semestre"
 OPTION_YEARLY:0 "Todo ano"
 OPTION_FIVE_YEAR:0 "Cada cinco anos"
 OPTION_NO_AUTOSAVE:0 "Não salvar automaticamente"
 SETTINGS_CATEGORY_ACCOUNT:0 "Conta"
 SETTINGS_CATEGORY_SYSTEM:0 "Sistema"
 SETTINGS_CATEGORY_CONTROLS:0 "Controles"
 SETTINGS_CATEGORY_CAMERA:0 "Câmera"
 SETTINGS_CATEGORY_AUDIO:0 "Áudio"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 RESTORE:0 "Restaurar"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "Definições"
 REQUIRES_RESTART:0 "Requer reinicialização"
 REQUIRE_RESTART_DESCRIPTION:0 "Algumas configurações não terão efeito até que você reinicie o jogo."
# Orphaned keys
 SETTING_REFRACTION_QUALITY:0 "Qualidade de Refração"
 SETTING_MAPOBJECT_QUALITY:0 "Qualidade de Objetos do Mapa"
